import asyncio
import os
from app.services.tagging_service import tagging_service

# 2024 CSAT Math Questions (Reconstructed from Search)
QUESTIONS = [
    {
        "id": "Q01",
        "text": r"$\sqrt[3]{24} \times 3^{\frac{2}{3}}$ 의 값은?",
        "answer": "6",
        "type": "Multiple Choice"
    },
    {
        "id": "Q22",
        "text": r"""
최고차항의 계수가 1인 삼차함수 $f(x)$에 대하여 실수 전체의 집합에서 정의된 함수 $g(x)$가
$$ g(x) = \begin{cases} f(x) & (x \ge t) \\ f(2t-x) & (x < t) \end{cases} $$
이다. 다음 조건을 만족시키는 모든 실수 $t$의 값의 합을 구하시오.

(가) 함수 $g(x)$는 실수 전체의 집합에서 미분가능하다.
(나) $g(x)$가 극댓값을 갖는 $x$의 개수는 1이다.
        """,
        "answer": "58", 
        "type": "Short Answer"
    }
]

async def generate_report():
    print("--- Q-DNA AI Analysis Report: 2024 CSAT Math ---")
    
    report_html = """
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Q-DNA AI Analysis: 2024 CSAT Math</title>
        <style>
            body { font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
            h1 { color: #1976d2; border-bottom: 2px solid #1976d2; padding-bottom: 10px; }
            .question-card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 25px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
            .metrics { display: flex; gap: 10px; margin-top: 15px; }
            .tag { background: #e3f2fd; color: #1976d2; padding: 4px 8px; border-radius: 12px; font-size: 0.85em; font-weight: bold; }
            .confidence { color: #666; font-size: 0.8em; margin-left: 4px; }
            .ai-insight { background: #f3f4f6; padding: 15px; border-left: 4px solid #4caf50; margin-top: 15px; border-radius: 0 4px 4px 0; }
        </style>
        <script>
        window.MathJax = {
          tex: {
            inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]
          }
        };
        </script>
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    </head>
    <body>
        <h1>Q-DNA AI Content Analysis Report</h1>
        <p><strong>Subject:</strong> 2024 College Scholastic Ability Test (Mathematics)</p>
        <p><strong>Generated By:</strong> Q-DNA Intelligence Engine</p>
        <hr/>
    """

    for q in QUESTIONS:
        print(f"Analyzing {q['id']}...")
        tags = await tagging_service.get_tag_recommendations(q['text'])
        
        # Determine Complexity based on tags
        is_hard = any(t['tag'] == 'High Difficulty' for t in tags)
        difficulty_stars = "★★★★★" if is_hard else "★★☆☆☆"
        
        tag_html = "".join([f"<span class='tag'>{t['tag']}<span class='confidence'>{int(t['confidence']*100)}%</span></span>" for t in tags])
        
        report_html += f"""
        <div class="question-card">
            <h3>Problem {q['id']} <span style="float:right; color:#f57c00;">{difficulty_stars}</span></h3>
            <p>{q['text']}</p>
            <div class="metrics">
                {tag_html}
            </div>
            <div class="ai-insight">
                <strong>AI Insight:</strong><br/>
                This problem requires an understanding of {', '.join([t['tag'] for t in tags[:2]])}.
                {'The logic involving differentiability of piecewise functions suggests a high discrimination index.' if is_hard else 'Standard calculation problem checking basic concept application.'}
            </div>
        </div>
        """

    report_html += """
    <div style="text-align: center; margin-top: 50px; color: #888;">
        &copy; 2024 Q-DNA System. All analysis performed by AI agents.
    </div>
    </body>
    </html>
    """

    # Save to public folder so browser can open it
    output_path = "../frontend/public/analysis_report.html"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_html)
    
    print(f"Report generated at: {output_path}")

if __name__ == "__main__":
    asyncio.run(generate_report())
